src/Entity/Picture.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PictureRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 * @ORM\Table(name="pictures")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */
class Picture
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(min=3)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     */
    private $description;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="picture_image", fileNameProperty="imageName")
     * @assert\Image(maxSize="8M")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="user", orphanRemoval=true)
     */
    private $pictures;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setUser($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getUser() === $this) {
                $picture->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' .$this->getLastName();
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PictureType.php
<?php

namespace App\Form;

use App\Entity\Picture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PictureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('imageFile', VichImageType::class, [
            'label' => 'Image (PNG or JPG file)',
            'required' => false,
            'allow_delete' => true,
            'delete_label' => 'Delete?',
            'download_uri' => false,
            'imagine_pattern' => 'squared_thumbnail_small'
        ])
        ->add('title')
        ->add('description')

       ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Picture::class,
        ]);
    }
}

src/Controller/PicturesController.php
<?php

namespace App\Controller;

use App\Entity\Picture;
use App\Form\PictureType;
use Doctrine\ORM\EntityManager;
use App\Repository\PictureRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PicturesController extends AbstractController
{

    private $em;

    public function __construct(EntityManagerInterface $em) 
    {
        $this->em = $em;
    }

    /**
     * @Route("/", name="app_home", methods="GET")
     //* @Route("/", name= "app_pictures_index")
     */
    public function index(PictureRepository $pictureRepository): Response
    {
        $pictures = $pictureRepository->findBy([], ['createdAt' => 'DESC']);

        return $this->render('pictures/index.html.twig', compact('pictures'));
    }

    /**
     * @Route("/pictures/create", name="app_pictures_create", methods="GET|POST")
     */
    public function create(Request $request, UserRepository $userRepo): Response
    {
        $picture = new Picture;

        $form = $this->createForm(PictureType::class, $picture);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $picture->setUser($this->getUser());
            $this->em->persist($picture);
            $this->em->flush();

            $this->addFlash('success', 'ArtWork successfully created!');

            return $this->redirectToRoute('app_home');

        }

        return $this->render('pictures/create.html.twig', [
            'form' => $form->createView()
        ]); 
    }

    /**
     * @Route("/pictures/{id<[0-9]+>}", name="app_pictures_show", methods="GET")
     */
    public function show(Picture $picture): Response 
    {
        return $this->render('pictures/show.html.twig', compact('picture'));
    }

    /**
     * @Route("/pictures/{id<[0-9]+>}/edit", name="app_pictures_edit", methods="GET|PUT")
     */
    public function edit(Request $request, Picture $picture): Response 
    {
        $form = $this->createForm(PictureType::class, $picture, [
            'method' => 'PUT',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->flush();

            $this->addFlash('success', 'ArtWork successfully updated!');


            return $this->redirectToRoute('app_home');

        }


        return $this->render('pictures/edit.html.twig', [
            'picture' => $picture,
            'form' => $form->createView()
        ]);
    }


        /**
     * @Route("/pictures/{id<[0-9]+>}", name="app_pictures_delete", methods="DELETE")
     */
    public function delete(Request $request, Picture $picture, EntityManagerInterface $em): Response 
    {
        if ($this->isCsrfTokenValid('picture_deletion_' . $picture->getId(), $request->request->get('csrf'))) {
            $em->remove($picture);
            $em->flush();

            $this->addFlash('info', 'ArtWork successfully deleted!');

        }

        return $this->redirectToRoute('app_home');
    }



}

templates/pictures/_form.html.twig
{{ form_start(form) }} 

    {{ form_widget(form) }}

    <input type="submit" value="{{ SubmitButtonText|default('Create Picture') }}" class="btn btn-primary btn-block" formnovalidate>

{{ form_end(form) }}

templates/pictures/create.html.twig
{% extends 'layouts/base.html.twig' %} 

{% block title 'New Picture' %} 

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto" >
            <h1>Create ArtWork</h1>

            {{ include('pictures/_form.html.twig') }}
        
        </div>
    </div>

{% endblock %}

templates/pictures/edit.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Edit Picture #' ~ picture.id %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto" >
            <h1>Edit Picture #{{ picture.id }}</h1>
             
            {{ include('pictures/_form.html.twig', { SubmitButtonText: 'Update Art' }) }}

        </div>
    </div>


{% endblock %}

templates/pictures/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title 'Virtual Exhibition v.1' %}

{% block body %}
    {% if pictures|length > 0 %}
        <h1 class="mb-3 text-center text-muted">{{ pluralize(pictures|length, 'ArtWork') }}</h1>

        <div class="text-center mb-3" >
            L'expérience coloniale photographiée en Nouvelle Calédonie et au Vanuatu......
        </div>

        {% for row in pictures|batch(3) %}
            <div class="row mb-5">
            {% for picture in row %}
                <div class="col-md-4">
                    <article class="picture bg-white rounded shadow">
                        <div class="mw-100 overflow-hidden rounded-top">
                            <a href="{{ path('app_pictures_show', {id: picture.id}) }}">
                                <img src="{{ (picture.imageName ? ('uploads/pictures/'~ picture.imageName) : asset('build/images/placeholder.jpg')) |
                                imagine_filter('squared_thumbnail_medium') }}" alt="{{ picture.title }}" 
                                class="w-100"/>
                            </a>
                        </div>
                        <h2 class="h5 pl-3 pt-3"><a href="{{ path('app_pictures_show', {id: picture.id}) }}" class="text-secondary text-decoration-none">{{ picture.title }}</a></h2>
                        <p class="pl-3 pb-3 text-muted "><small>Submitted by {{ picture.user.fullName}}</small></p>
                    </article>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <p class="h1 mt-5 text-center">No Artwork yet. <a href="{{ path('app_pictures_create') }}">Be the first!</a></p>
    {% endif %}
{% endblock %}

templates/pictures/show.html.twig
{% extends 'layouts/base.html.twig' %} 

{% block title picture.title %} 

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto ">
            <article class="picture bg-white rounded shadow">
                <div class="mw-100 overflow-hidden rounded-top">
                    <img src="{{ (picture.imageName ? ('uploads/pictures/'~ picture.imageName) : asset('build/images/placeholder.jpg')) |
                    imagine_filter('squared_thumbnail_medium') }}" alt="{{ picture.title }}" 
                    class="w-100"/>
                </div>
                <div class="p-3">
                    <h1 class="h5 text-secondary">{{ picture.title }}</h1>
                    <p class="text-muted ">
                        <small>
                            Submitted {{ picture.createdAt|date('Y-m-d H:i:s') }}
                            by {{ picture.user.fullName}}
                        </small>
                    </p>

                    <p class="pt-3 text-break">
                        {{ picture.description }}
                    </p>

                    <div class="pt-3">
                        <a href="{{ path('app_pictures_edit', {id: picture.id}) }}" class="btn btn-light">Edit Artwork</a>
                        <a href="#" onclick="event.preventDefault(); confirm('Are you sure?') && document.getElementById('js_picture_delete_form').submit();" class="btn btn-light">Delete Artwork</a>

                        <form id="js_picture_delete_form" action="{{ path('app_pictures_delete', {id:picture.id}) }}" method="POST" style="display: none;">
                            <input type="text" name="csrf" value="{{ csrf_token('picture_deletion_' ~ picture.id) }}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form>
                    </div>
                </div>
            </article>
        </div>
    </div>

{% endblock %}